#!/bin/sh

success=true

echo
echo "=== black ==="
black --check --extend-exclude venv . || success=false

echo
echo "=== bandit ==="
bandit -c bandit.yml --exclude ./venv/ -r . || success=false

echo
echo "=== mypy ==="
mypy --exclude '(^venv/)|(^setup\.py$)' . || success=false

echo
echo "=== pylint ==="
find . -name venv -prune -o -name "*.py" -exec pylint {} \; || success=false

$success
